# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68d4b350881bfa1b498bddd0d7273746bd51af99b3e2f2d55e5ac30bd6a083dc5562c7d4c7b5e66f063183cd7076c25d3882190427276827c893ac8ed0ff3adf

test:
  secret_key_base: fb025f053ba72ecde711c6a3c896188f7cdde61eeb47b9fe0449610ba6e336760401c97bd988e54783b02ced6a4c60f2832050388cda3d9dec92762354f0d330

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
